---
# Full documentation: https://ansible-lint.readthedocs.io/en/latest/index.html
exclude_paths:
  - ../../.cache/
  - .cache/
  - .github/
  - .hooks/
  - .vscode/
  - archived_data/
  - galaxy-roles/

skip_list:
  - command-instead-of-shell
  - name[template]
  - ignore-errors
  - meta-incorrect
  - meta-no-info
  - package-latest
  - role-name
  - unnamed-task
  - var-naming
  - name[casing]

warn_list:
  - experimental
  - risky-file-permissions
  - command-instead-of-module
